version: '3'

services:
  db:
    container_name: db
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bfdiscordbot
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app

  app:
    container_name: bot
    build:
      context: .
    env_file:
      - .env
    environment:
      NODE_ENV: ${ENV:-production}
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app

networks:
  app:

volumes:
  db_data: